// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Picker is an autogenerated mock type for the Picker type
type Picker struct {
	mock.Mock
}

// Pick provides a mock function with given fields: origin
func (_m *Picker) Pick(origin string) string {
	ret := _m.Called(origin)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(origin)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Set provides a mock function with given fields: proxies
func (_m *Picker) Set(proxies ...string) {
	_va := make([]interface{}, len(proxies))
	for _i := range proxies {
		_va[_i] = proxies[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
